# Generated by Django 3.1.1 on 2020-09-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_ID', models.CharField(max_length=100)),
                ('cus_PW', models.CharField(max_length=100)),
                ('cus_name', models.CharField(max_length=100)),
                ('cus_address', models.CharField(max_length=500)),
                ('cus_RRN', models.CharField(max_length=6)),
                ('cus_phone_number', models.CharField(max_length=13)),
            ],
        ),
    ]
