# Generated by Django 3.1.1 on 2020-09-24 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='input_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
