# Generated by Django 3.1.1 on 2020-10-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0003_campaign_project_project_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cam_id',
            new_name='cam',
        ),
        migrations.RenameField(
            model_name='project_detail',
            old_name='pro_id',
            new_name='pro',
        ),
    ]
