# Generated by Django 3.1.1 on 2020-10-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0004_auto_20201005_1533'),
    ]

    operations = [
    ]
