# Generated by Django 3.1.1 on 2020-10-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0006_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
