# Generated by Django 3.1.1 on 2020-10-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0007_delete_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cam',
        ),
        migrations.RemoveField(
            model_name='project_detail',
            name='pro',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Project_Detail',
        ),
    ]
