# Generated by Django 3.1.1 on 2020-10-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0008_auto_20201006_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('cam_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField(blank=True, max_length=500, null=True)),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
