# Generated by Django 3.1.1 on 2020-10-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0009_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
