# Generated by Django 3.1.1 on 2020-10-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0010_auto_20201006_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(upload_to='static/campaign_img'),
        ),
    ]
