# Generated by Django 3.1.1 on 2020-10-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0012_campaign_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='image',
        ),
    ]
