# Generated by Django 3.1.1 on 2020-10-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0013_remove_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(default=1, upload_to='static/campaign_img'),
            preserve_default=False,
        ),
    ]
