# Generated by Django 3.1.1 on 2020-10-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0015_auto_20201007_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.ImageField(upload_to='static/campaign_img'),
        ),
    ]
