# Generated by Django 3.1.1 on 2020-10-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0016_auto_20201007_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_title', models.CharField(max_length=100)),
                ('pro_content', models.TextField()),
                ('pro_inputer', models.CharField(max_length=50)),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('cam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoodData.campaign')),
            ],
        ),
    ]
