# Generated by Django 3.1.1 on 2020-10-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0017_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cam',
            new_name='campaign',
        ),
    ]
