# Generated by Django 3.1.1 on 2020-10-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0018_auto_20201008_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Detail',
            fields=[
                ('pro_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_ID', models.CharField(max_length=100)),
                ('real_filename', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('filepath', models.CharField(max_length=100)),
                ('filesize', models.CharField(max_length=250)),
                ('pro_detail_title', models.CharField(max_length=100)),
                ('pro_detail_content', models.TextField()),
                ('pro_detail_inputer', models.CharField(max_length=50)),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoodData.project')),
            ],
        ),
    ]
