# Generated by Django 3.1.1 on 2020-10-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0024_auto_20201013_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_detail',
            name='pro_order',
            field=models.IntegerField(default=1),
        ),
    ]
