# Generated by Django 3.1.1 on 2020-10-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0025_project_detail_pro_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_detail',
            name='boolean',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
