# Generated by Django 3.1.1 on 2020-10-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0026_project_detail_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_detail',
            name='boolean',
        ),
        migrations.AddField(
            model_name='project_detail',
            name='user1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_detail',
            name='user2',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_detail',
            name='user3',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_detail',
            name='user4',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project_detail',
            name='user5',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
