# Generated by Django 3.1.1 on 2020-10-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0029_auto_20201014_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_detail',
            name='YN1',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project_detail',
            name='YN2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project_detail',
            name='YN3',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project_detail',
            name='YN4',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='project_detail',
            name='YN5',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
