# Generated by Django 3.1.1 on 2020-10-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0035_auto_20201015_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
