# Generated by Django 3.1.1 on 2020-10-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0036_customer_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_detail',
            name='video',
            field=models.FileField(upload_to='static/project_video'),
        ),
    ]
