# Generated by Django 3.1.1 on 2020-10-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0037_auto_20201018_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='facebook_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='facebook_uid',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='google_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='google_uid',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='naver_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='naver_uid',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
