# Generated by Django 3.1.1 on 2020-10-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0038_auto_20201027_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='facebook_provider',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='google_provider',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='naver_provider',
        ),
    ]
