# Generated by Django 3.1.1 on 2020-10-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0039_auto_20201027_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Friends',
            fields=[
                ('friends_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('friend_id', models.CharField(max_length=100)),
                ('friend_name', models.CharField(max_length=100)),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoodData.customer')),
            ],
        ),
    ]
