# Generated by Django 3.1.1 on 2020-10-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0040_user_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_friends',
            old_name='user',
            new_name='cus_ID',
        ),
        migrations.RenameField(
            model_name='user_friends',
            old_name='user_name',
            new_name='cus_name',
        ),
    ]
