# Generated by Django 3.1.1 on 2020-10-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0041_auto_20201029_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_friends',
            name='cus_idx',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GoodData.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_friends',
            name='cus_ID',
            field=models.CharField(max_length=100),
        ),
    ]
