# Generated by Django 3.1.1 on 2020-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0043_customer_cus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_image',
            field=models.ImageField(blank=True, default='static/customer_img/profile_photo.jpg', upload_to='static/customer_img'),
        ),
    ]
