# Generated by Django 3.1.1 on 2020-10-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0047_auto_20201030_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_image',
            field=models.ImageField(default='media/customer_img/profile_photo.jpg', upload_to='media/customer_img'),
        ),
    ]
