# Generated by Django 3.1.1 on 2020-11-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0052_auto_20201102_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_version',
            fields=[
                ('app_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
            ],
        ),
    ]
