# Generated by Django 3.1.1 on 2020-11-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0053_app_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='key_number',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
