# Generated by Django 3.1.1 on 2020-11-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0054_customer_key_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cus_RRN',
        ),
    ]
