# Generated by Django 3.1.1 on 2020-11-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0056_campaign_font_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='font_color',
            field=models.CharField(choices=[('blue', 'blue'), ('green', 'green'), ('red', 'red')], default='', max_length=30),
        ),
    ]
