# Generated by Django 3.1.1 on 2020-11-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0057_auto_20201116_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='font_color',
            field=models.CharField(choices=[('purple', 'purple'), ('maroon', 'maroon'), ('aqua', 'aqua'), ('silver', 'silver'), ('navy', 'navy'), ('teal', 'teal'), ('green', 'green'), ('gray', 'gray'), ('red', 'red'), ('yellow', 'yellow'), ('fuchsia', 'fuchsia'), ('black', 'black'), ('blue', 'blue'), ('lime', 'lime'), ('olive', 'olive')], default='', max_length=30),
        ),
    ]
