# Generated by Django 3.1.1 on 2020-11-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0059_auto_20201116_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='font_color',
            field=models.CharField(choices=[('olive', 'olive'), ('teal', 'teal'), ('purple', 'purple'), ('fuchsia', 'fuchsia'), ('navy', 'navy'), ('silver', 'silver'), ('gray', 'gray'), ('blue', 'blue'), ('aqua', 'aqua'), ('maroon', 'maroon'), ('lime', 'lime'), ('black', 'black'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow')], default='', max_length=30),
        ),
    ]
