# Generated by Django 3.1.1 on 2020-11-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0060_auto_20201116_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='font_color',
            field=models.CharField(choices=[('aqua', 'aqua'), ('yellow', 'yellow'), ('purple', 'purple'), ('gray', 'gray'), ('silver', 'silver'), ('teal', 'teal'), ('red', 'red'), ('black', 'black'), ('olive', 'olive'), ('fuchsia', 'fuchsia'), ('navy', 'navy'), ('blue', 'blue'), ('maroon', 'maroon'), ('green', 'green'), ('lime', '#edffff')], default='', max_length=30),
        ),
    ]
