# Generated by Django 3.1.1 on 2020-11-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0062_auto_20201117_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='font_color',
            field=models.CharField(choices=[('#f9f9f9', 'olive'), ('#dadada', 'yellow'), ('#e8e8e8', 'purple'), ('#e2e2e2', 'silver'), ('#e2e1e1', 'aqua'), ('#efefef', 'teal'), ('#f5f5f5', 'blue'), ('#d4d4d4', 'gray'), ('#c7c7c7', 'fuchsia'), ('#f1f1f1', 'red'), ('#d6d6d6', 'black'), ('#d2d2d2', 'navy'), ('#f3f3f3', 'maroon'), ('#ececec', 'green'), ('#edffff', 'lime')], default='', max_length=30),
        ),
    ]
