# Generated by Django 3.1.1 on 2020-11-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0063_auto_20201119_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='font_color',
            field=models.CharField(choices=[('#d1c7e6', 'gray'), ('#bde6f3', 'teal'), ('#ced8e4', 'blue'), ('#adc9e2', 'black'), ('#fdeaea', 'purple'), ('#e0edf1', 'silver'), ('#b3bef9', 'olive'), ('#eaf3fd', 'red'), ('#cdcce0', 'yellow'), ('##e2e6fb', 'lime'), ('#d0d0d0', 'navy'), ('#c1e3ff', 'fuchsia'), ('#c7cfff', 'aqua'), ('#efefef', 'maroon'), ('#b7d5f7', 'green')], default='', max_length=30),
        ),
    ]
