# Generated by Django 3.1.1 on 2020-11-20 17:11

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0065_auto_20201120_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='background_color2',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='background_color',
            field=models.CharField(choices=[('#d1c7e6', 'gray'), ('#adc9e2', 'black'), ('#e2e6fb', 'lime'), ('#b7d5f7', 'green'), ('#d0d0d0', 'navy'), ('#fdeaea', 'purple'), ('#e0edf1', 'silver'), ('#c1e3ff', 'fuchsia'), ('#eaf3fd', 'sky'), ('#efefef', 'maroon'), ('#bde6f3', 'teal'), ('#c7cfff', 'aqua'), ('#cdcce0', 'yellow'), ('#b3bef9', 'olive'), ('#ced8e4', 'blue')], default='', max_length=30),
        ),
    ]
