# Generated by Django 3.1.1 on 2020-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0066_auto_20201120_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='background_color2',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='background_color',
            field=models.CharField(choices=[('#eaf3fd', '시청'), ('#bde6f3', 'teal'), ('#efefef', 'maroon'), ('#adc9e2', 'black'), ('#fdeaea', 'purple'), ('#b3bef9', 'olive'), ('#ced8e4', '위원회'), ('#c7cfff', '공사'), ('#d1c7e6', 'gray'), ('#c1e3ff', 'fuchsia'), ('#e0edf1', 'silver'), ('#cdcce0', 'yellow'), ('#e2e6fb', 'lime'), ('#b7d5f7', '공단'), ('#d0d0d0', 'navy')], default='', max_length=30),
        ),
    ]
