# Generated by Django 3.1.1 on 2020-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0067_auto_20201120_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='background_color',
            field=models.CharField(choices=[('#cdcce0', 'yellow'), ('#ced8e4', '위원회'), ('#b7d5f7', '공단 & 공사'), ('#bde6f3', 'teal'), ('#c1e3ff', 'fuchsia'), ('#efefef', 'maroon'), ('#e0edf1', 'silver'), ('#adc9e2', 'black'), ('#b3bef9', 'olive'), ('#d1c7e6', '소방청'), ('#d0d0d0', '센터'), ('#fdeaea', '연합회'), ('#eaf3fd', '시청'), ('#e2e6fb', '경찰청'), ('#c7cfff', 'red')], default='', max_length=30),
        ),
    ]
