# Generated by Django 3.1.1 on 2020-11-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoodData', '0068_auto_20201120_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='background_color',
            field=models.CharField(choices=[('#c1e3ff', '재단'), ('#c7cfff', '지자체'), ('#e2e6fb', '경찰청'), ('#d0d0d0', '센터'), ('#efefef', '진흥원'), ('#eaf3fd', '시청'), ('#b3bef9', '정당'), ('#cdcce0', '행정부'), ('#adc9e2', '연구기관'), ('#fdeaea', '연합회'), ('#d1c7e6', '소방청'), ('#bde6f3', '법원'), ('#e0edf1', '공사'), ('#ced8e4', '위원회'), ('#b7d5f7', '공단')], default='', max_length=30),
        ),
    ]
